/*
 * This source file was generated by the Gradle 'init' task
 */
package projetos;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

public class RaycasterEngineTest {
    @Test
    public void testRaycasterEngineInitialization() {
        RaycasterEngine engine = new RaycasterEngine();
        assertNotNull(engine, "RaycasterEngine should be initialized");
    }
}